/**
 * Single source of truth for personal identity, contact copy, and the SEO
 * metadata used to build the document head + structured data. Reuse these
 * everywhere instead of hardcoding name/email/links so there's one place to
 * update.
 */
export const SITE = {
  name: "Gabriel Mouallem",
  firstName: "Gabriel",
  lastName: "Mouallem",
  /** Monogram initials, e.g. logo mark "GM". */
  initials: "GM",
  title: "Product & Software Engineer",

  /** Browser tab / <title> — front-loads name + role so the highest-value
   * keywords lead, and stays ≤60 chars so Google doesn't truncate it in
   * SERPs (the broader skill stack lives in the meta description instead). */
  pageTitle: "Gabriel Mouallem — Senior Product & Software Engineer",

  /** Meta description — kept inside the ~50–160 char SERP window so it isn't
   * truncated. Keyword-dense but readable; states the LATAM/remote-contract
   * angle that the visual page only implies. */
  description:
    "Senior Product & Software Engineer from Brazil (LATAM). 7+ years in full-stack React, Next.js, Node.js, Python & Kubernetes. Open to remote & contract roles.",

  /** Longer blurb for Open Graph / structured data, where length is less
   * constrained and the extra context helps relevance + social previews. */
  longDescription:
    "Senior Product & Software Engineer based in Brazil (LATAM), available for remote and contract engagements with US and international teams. 7+ years shipping full-stack products with React, Next.js, TypeScript, Node.js and Python, plus cloud-native infrastructure on Kubernetes (managed PostgreSQL DBaaS, CloudNativePG, observability, SOC 2). Background spanning IoT, AI/computer-vision video platforms and bare-metal cloud.",

  /** Production URL (canonical / Open Graph). Kept absolute so it's correct
   * regardless of the base-path build mode. */
  url: "https://gabrielm.dev/",

  /** Social-share card (Open Graph / Twitter). Generated by
   * `scripts/generate-og.mjs` into public/. */
  ogImage: "/og-image.png",

  /** Where the engineer is based + the markets he serves. Surfaced in the
   * structured-data address and the keyword copy. */
  location: {
    city: "Itajubá",
    region: "Minas Gerais",
    country: "Brazil",
    countryCode: "BR",
  },

  /** Keyword set — a mix of explicit skills and the implicit
   * hiring/sourcing terms (LATAM, nearshore, outsourcing, staff
   * augmentation, remote contractor) that prospective clients search for
   * but that the visual design never spells out. All truthful: a
   * Brazil-based engineer who has shipped remotely for US companies. */
  keywords: [
    "Gabriel Mouallem",
    "Product Engineer",
    "Software Engineer",
    "Senior Software Engineer",
    "Full-Stack Developer",
    "React developer",
    "Next.js developer",
    "TypeScript",
    "Node.js",
    "Python developer",
    "Django",
    "FastAPI",
    "NestJS",
    "React Native",
    "Kubernetes",
    "Cloud Native",
    "DevOps",
    "PostgreSQL",
    "DBaaS",
    "CloudNativePG",
    "IoT",
    "AI",
    "computer vision",
    "remote software engineer",
    "contract software engineer",
    "freelance software engineer",
    "hire software engineer",
    "LATAM software engineer",
    "Latin America developer",
    "Brazil software engineer",
    "nearshore software development",
    "nearshore outsourcing",
    "software outsourcing",
    "staff augmentation",
    "offshore development",
  ],

  email: "gabriel.unifei2017@gmail.com",
  links: {
    linkedin: "https://www.linkedin.com/in/gabriel-mouallem/",
    github: "https://github.com/gabrielmouallem",
    resume: "/Gabriel_Mouallem_Product_Engineer_Resume.pdf",
  },
  /** Suggested filename for the résumé download attribute. */
  resumeFileName: "Gabriel_Mouallem_Product_Engineer_Resume.pdf",
  /** Standardized download CTA copy — reused by the nav button and the
   * About modal so the wording stays in sync everywhere. */
  resumeLabel: "Download CV",
} as const;
